/* A polyfill for old browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'uiFontLiga' to the window object. You can pass element references to this method.
*/
(function () {
	'use strict';
	function supportsProperty(p) {
		var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
			i,
			div = document.createElement('div'),
			ret = p in div.style;
		if (!ret) {
			p = p.charAt(0).toUpperCase() + p.substr(1);
			for (i = 0; i < prefixes.length; i += 1) {
				ret = prefixes[i] + p in div.style;
				if (ret) {
					break;
				}
			}
		}
		return ret;
	}
	var icons;
	if (!supportsProperty('fontFeatureSettings')) {
		icons = {
			'arrow-down': '&#xCD111;',
			'arrow-up': '&#xCD112;',
			'caret-right': '&#xCD113;',
			'caret-left': '&#xCD114;',
			'arrow-circle-down': '&#xCD115;',
			'arrow-circle-up': '&#xCD116;',
			'arrow-o-circle-right': '&#xCD117;',
			'arrow-o-circle-left': '&#xCD118;',
			'caret-o-circle-left': '&#xCD121;',
			'caret-o-circle-right': '&#xCD122;',
			'arrow-circle-right': '&#xCD123;',
			'arrow-circle-left': '&#xCD124;',
			'caret-circle-left': '&#xCD125;',
			'caret-circle-right': '&#xCD126;',
			'check-o-circle': '&#xCD127;',
			'delete-o-circle': '&#xCD128;',
			'check-circle': '&#xCD131;',
			'delete-circle': '&#xCD132;',
			'return-left': '&#xCD133;',
			'return-right': '&#xCD134;',
			'traffic': '&#xCD135;',
			'back': '&#xCD136;',
			'forward': '&#xCD137;',
			'contract': '&#xCD138;',
			'expand': '&#xCD141;',
			'exit-fullscreen': '&#xCD142;',
			'expand-window': '&#xCD143;',
			'refresh': '&#xCD144;',
			'sync': '&#xCD145;',
			'cycle': '&#xCD146;',
			'repeat': '&#xCD147;',
			'bar-chart': '&#xCD148;',
			'bar-chart-up': '&#xCD151;',
			'stats-up': '&#xCD152;',
			'stats-down': '&#xCD153;',
			'stats-easel-up': '&#xCD154;',
			'stats-easel-down': '&#xCD155;',
			'bar-chart-easel': '&#xCD156;',
			'window-down': '&#xCD157;',
			'window-up': '&#xCD158;',
			'window-maximize': '&#xCD161;',
			'window-minimize': '&#xCD162;',
			'login': '&#xCD163;',
			'logout': '&#xCD164;',
			'panel-close': '&#xCD165;',
			'panel-show': '&#xCD166;',
			'window': '&#xCD168;',
			'window-plus': '&#xCD171;',
			'window-minus': '&#xCD172;',
			'window-check': '&#xCD173;',
			'window-delete': '&#xCD174;',
			'share-right': '&#xCD175;',
			'share-left': '&#xCD176;',
			'multiple-windows': '&#xCD177;',
			'grid-lg': '&#xCD182;',
			'list-th-lg': '&#xCD183;',
			'sidebar': '&#xCD184;',
			'list-bullet': '&#xCD185;',
			'bars': '&#xCD186;',
			'outdent': '&#xCD187;',
			'indent': '&#xCD188;',
			'document': '&#xCD211;',
			'text-doc': '&#xCD212;',
			'zipped-doc': '&#xCD213;',
			'text-doc-plus': '&#xCD214;',
			'text-doc-minus': '&#xCD215;',
			'heart-card': '&#xCD216;',
			'diamond-card': '&#xCD217;',
			'spade-card': '&#xCD218;',
			'club-card': '&#xCD221;',
			'book': '&#xCD222;',
			'clipboard': '&#xCD223;',
			'check-clipboard': '&#xCD224;',
			'delete-clipboard': '&#xCD225;',
			'text-clipboard': '&#xCD226;',
			'address-book': '&#xCD227;',
			'calendar': '&#xCD228;',
			'calendar-day': '&#xCD231;',
			'id-card': '&#xCD232;',
			'polaroids': '&#xCD233;',
			'polaroids-blank': '&#xCD234;',
			'photos': '&#xCD235;',
			'photo': '&#xCD236;',
			'camera': '&#xCD237;',
			'headphones': '&#xCD238;',
			'stop': '&#xCD241;',
			'play': '&#xCD242;',
			'record': '&#xCD243;',
			'pause': '&#xCD244;',
			'ffw': '&#xCD245;',
			'rev': '&#xCD246;',
			'skip-forward': '&#xCD247;',
			'skip-back': '&#xCD248;',
			'eject': '&#xCD251;',
			'volume-max': '&#xCD253;',
			'volume-min': '&#xCD254;',
			'mute': '&#xCD255;',
			'volume-plus': '&#xCD256;',
			'volume-minus': '&#xCD257;',
			'volume-delete': '&#xCD258;',
			'music-notes': '&#xCD261;',
			'music-notes-box': '&#xCD262;',
			'speaker': '&#xCD263;',
			'boombox': '&#xCD264;',
			'ipod': '&#xCD265;',
			'microphone': '&#xCD266;',
			'microphone-alt': '&#xCD267;',
			'cd': '&#xCD268;',
			'vinyl': '&#xCD271;',
			'cassette': '&#xCD272;',
			'eq': '&#xCD273;',
			'slate': '&#xCD274;',
			'film': '&#xCD275;',
			'tv': '&#xCD276;',
			'monitor': '&#xCD277;',
			'printer': '&#xCD281;',
			'printing': '&#xCD282;',
			'mouse': '&#xCD283;',
			'text': '&#xCD284;',
			'ribbon': '&#xCD285;',
			'gamepad': '&#xCD286;',
			'portable-game': '&#xCD287;',
			'tablet': '&#xCD288;',
			'calculator': '&#xCD311;',
			'floppy-disc': '&#xCD312;',
			'bell': '&#xCD314;',
			'hourglass': '&#xCD315;',
			'smartphone': '&#xCD316;',
			'cellphone': '&#xCD317;',
			'lightbulb': '&#xCD318;',
			'telephone': '&#xCD321;',
			'battery-full': '&#xCD322;',
			'battery-half': '&#xCD323;',
			'battery-low': '&#xCD324;',
			'battery-charge': '&#xCD325;',
			'flashlight': '&#xCD326;',
			'wrench': '&#xCD327;',
			'settings': '&#xCD328;',
			'zoom-in': '&#xCD331;',
			'zoom-out': '&#xCD332;',
			'search': '&#xCD333;',
			'cloud-upload': '&#xCD335;',
			'cloud-up': '&#xCD336;',
			'cloud-down': '&#xCD337;',
			'cloud-check': '&#xCD338;',
			'cloud-delete': '&#xCD341;',
			'bluetooth': '&#xCD342;',
			'wifi': '&#xCD343;',
			'firewire': '&#xCD344;',
			'usb': '&#xCD345;',
			'plug': '&#xCD346;',
			'outlet': '&#xCD347;',
			'command-line': '&#xCD348;',
			'shuffle': '&#xCD351;',
			'ethernet': '&#xCD352;',
			'code': '&#xCD353;',
			'fullscreen': '&#xCD354;',
			'contrast': '&#xCD355;',
			'coverflow': '&#xCD356;',
			'zoom-out-solid': '&#xCD357;',
			'zoom-in-solid': '&#xCD358;',
			'info': '&#xCD361;',
			'info-circle': '&#xCD362;',
			'outbox': '&#xCD363;',
			'inbox': '&#xCD364;',
			'download': '&#xCD365;',
			'compose': '&#xCD366;',
			'layout': '&#xCD367;',
			'link': '&#xCD368;',
			'windows': '&#xCD371;',
			'flash-drive': '&#xCD372;',
			'location': '&#xCD373;',
			'bus': '&#xCD374;',
			'train': '&#xCD375;',
			'gas': '&#xCD376;',
			'dashboard': '&#xCD377;',
			'dashboard-alt': '&#xCD378;',
			'flag': '&#xCD381;',
			'flag-alt': '&#xCD382;',
			'plane': '&#xCD383;',
			'compass': '&#xCD384;',
			'clock': '&#xCD385;',
			'watch': '&#xCD386;',
			'alarm-clock': '&#xCD387;',
			'megaphone': '&#xCD388;',
			'locked-alt': '&#xCD411;',
			'unlocked-alt': '&#xCD412;',
			'locked': '&#xCD413;',
			'unlocked': '&#xCD414;',
			'keyboard': '&#xCD415;',
			'cube-open': '&#xCD416;',
			'cube': '&#xCD417;',
			'mailbox': '&#xCD418;',
			'file-drawer': '&#xCD421;',
			'folder-flat': '&#xCD422;',
			'folder': '&#xCD423;',
			'folder-plus': '&#xCD424;',
			'folder-minus': '&#xCD425;',
			'attach': '&#xCD426;',
			'recycle': '&#xCD427;',
			'recycle-bin': '&#xCD428;',
			'envelope': '&#xCD431;',
			'mail': '&#xCD432;',
			'mail-down': '&#xCD433;',
			'mail-up': '&#xCD434;',
			'check': '&#xCD435;',
			'delete': '&#xCD436;',
			'map': '&#xCD437;',
			'brush': '&#xCD438;',
			'pen': '&#xCD441;',
			'pencil': '&#xCD442;',
			'thumbtack': '&#xCD443;',
			'male': '&#xCD444;',
			'female': '&#xCD445;',
			'brightness-up': '&#xCD446;',
			'brightness-down': '&#xCD447;',
			'crosshair': '&#xCD448;',
			'trefoil-circle': '&#xCD451;',
			'cross-circle': '&#xCD452;',
			'power': '&#xCD453;',
			'pie-chart': '&#xCD454;',
			'share': '&#xCD455;',
			'move': '&#xCD456;',
			'star-6': '&#xCD457;',
			'star-5': '&#xCD458;',
			'alert-o': '&#xCD461;',
			'alert': '&#xCD462;',
			'option': '&#xCD463;',
			'plus': '&#xCD464;',
			'minus': '&#xCD465;',
			'user': '&#xCD466;',
			'group': '&#xCD467;',
			'user-plus': '&#xCD468;',
			'user-minus': '&#xCD471;',
			'user-delete': '&#xCD472;',
			'chat': '&#xCD473;',
			'chat-dots': '&#xCD474;',
			'chat-rect': '&#xCD475;',
			'chat-rect-dots': '&#xCD476;',
			'chat-lines': '&#xCD477;',
			'chat-rect-lines': '&#xCD478;',
			'infinity': '&#xCD481;',
			'umbrella': '&#xCD482;',
			'necktie': '&#xCD483;',
			'briefcase': '&#xCD484;',
			'first-aid': '&#xCD485;',
			'capsule': '&#xCD486;',
			'shield': '&#xCD487;',
			'mustache': '&#xCD488;',
			'bag': '&#xCD511;',
			'tag': '&#xCD512;',
			'credit-card': '&#xCD513;',
			'planet': '&#xCD514;',
			'earth': '&#xCD515;',
			'globe': '&#xCD516;',
			'trophy': '&#xCD517;',
			'medal': '&#xCD518;',
			'trashcan': '&#xCD521;',
			'trefoil': '&#xCD522;',
			'leaf': '&#xCD523;',
			'lamp': '&#xCD524;',
			'home': '&#xCD525;',
			'help': '&#xCD526;',
			'magnet': '&#xCD527;',
			'heart': '&#xCD528;',
			'd6': '&#xCD531;',
			'asterisk': '&#xCD532;',
			'flask': '&#xCD533;',
			'flask-tilted': '&#xCD534;',
			'test-tube': '&#xCD535;',
			'mallet': '&#xCD536;',
			'fork-spoon': '&#xCD537;',
			'spatula': '&#xCD538;',
			'chef-hat': '&#xCD541;',
			'place-setting': '&#xCD542;',
			'knife-fork': '&#xCD543;',
			'grill-open': '&#xCD544;',
			'grill': '&#xCD545;',
			'platter': '&#xCD546;',
			'droplet': '&#xCD547;',
			'wine': '&#xCD548;',
			'wine-tilted': '&#xCD551;',
			'drink': '&#xCD552;',
			'drink-straw': '&#xCD553;',
			'popsicle': '&#xCD554;',
			'popsicle-eaten': '&#xCD555;',
			'ice-cream': '&#xCD556;',
			'ice-cream-alt': '&#xCD557;',
			'ice-cream-eaten-alt': '&#xCD558;',
			'ice-cream-eaten': '&#xCD561;',
			'mug': '&#xCD562;',
			'noodle-bowl': '&#xCD563;',
			'bowl': '&#xCD564;',
			'bowl-spoon': '&#xCD565;',
			'apple': '&#xCD566;',
			'apple-eaten': '&#xCD567;',
			'pizza': '&#xCD568;',
			'pizza-eaten': '&#xCD571;',
			'drumstick': '&#xCD572;',
			'drumstick-eaten': '&#xCD573;',
			'muffin': '&#xCD574;',
			'mustard': '&#xCD575;',
			'mustard-alt': '&#xCD576;',
			'ketchup': '&#xCD577;',
			'sauce': '&#xCD578;',
			'egg': '&#xCD581;',
			'fish': '&#xCD582;',
			'fridge': '&#xCD583;',
			'eye': '&#xCD584;',
			'glasses': '&#xCD585;',
			'crown': '&#xCD586;',
			'king': '&#xCD587;',
			'notepad': '&#xCD588;'
		};
		delete icons['0'];
		window.uiFontLiga = function (els) {
			var classes,
				el,
				i,
				innerHTML,
				key;
			els = els || document.getElementsByTagName('*');
			if (!els.length) {
				els = [els];
			}
			for (i = 0; ; i += 1) {
				el = els[i];
				if (!el) {
					break;
				}
				classes = el.className;
				if (/icon-/.test(classes)) {
					innerHTML = el.innerHTML;
					if (innerHTML && innerHTML.length > 1) {
						for (key in icons) {
							if (icons.hasOwnProperty(key)) {
								innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
							}
						}
						el.innerHTML = innerHTML;
					}
				}
			}
		};
		window.uiFontLiga();
	}
}());