# Site
name: Screenplay
description: Product Design with Stories in Mind
meta_description: "Product Design with Stories in Mind"
logo: 'assets/images/logo-screenplay.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: 
email: 'parveenj@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  pj:
    name: Parveen
    display_name: PJ
    gravatar: 
    email: parveenj@gmail.com
    web: https://www.storyagent.design
    twitter: https://twitter.com/in/parveenj
    description: "Product Design Leader in Silicon Valley"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge